// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs1oBOwpM9NUYYsG1yHuNDay-ItaHtLPE',
    appId: '1:728811110678:web:74113dfeaa90d41dfdd037',
    messagingSenderId: '728811110678',
    projectId: 'fruit-hub-1fb78',
    authDomain: 'fruit-hub-1fb78.firebaseapp.com',
    storageBucket: 'fruit-hub-1fb78.firebasestorage.app',
    measurementId: 'G-5CTENWRB16',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWuBCO9F7hlgxqza1eoBiYsOVB6QhFQAI',
    appId: '1:728811110678:android:a5432e3364fa273dfdd037',
    messagingSenderId: '728811110678',
    projectId: 'fruit-hub-1fb78',
    storageBucket: 'fruit-hub-1fb78.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfNl_NY-8DzB7_Yu65_Qq1OHVQVEN-xWg',
    appId: '1:728811110678:ios:6a5ae4056b93bfc3fdd037',
    messagingSenderId: '728811110678',
    projectId: 'fruit-hub-1fb78',
    storageBucket: 'fruit-hub-1fb78.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfNl_NY-8DzB7_Yu65_Qq1OHVQVEN-xWg',
    appId: '1:728811110678:ios:6a5ae4056b93bfc3fdd037',
    messagingSenderId: '728811110678',
    projectId: 'fruit-hub-1fb78',
    storageBucket: 'fruit-hub-1fb78.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCs1oBOwpM9NUYYsG1yHuNDay-ItaHtLPE',
    appId: '1:728811110678:web:33b1a74da94a8ab7fdd037',
    messagingSenderId: '728811110678',
    projectId: 'fruit-hub-1fb78',
    authDomain: 'fruit-hub-1fb78.firebaseapp.com',
    storageBucket: 'fruit-hub-1fb78.firebasestorage.app',
    measurementId: 'G-9XQ39H027Q',
  );
}
